### PR TITLE
ifeellucky > any

### PR DESCRIPTION
**Pull request by ALIENQuake**

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
nah, it's a fitting name.

**Comment by ALIENQuake** [comment]
@lynxlynxlynx Seriously? You want to tell me that people won't freak-out when they see "LUCKY" in the link name? It's not professional for any software to indicate a luck factor like cards/casino etc And it's not 'luck', players will always the correct mod package because it depends on mod author to switch to releases or not. Please accept this change.

**Comment by lynxlynxlynx** [comment]
You give way too much credit to modders and this logic. It's deterministic only in an ideal world, so people should not trust it. You do not know what you will get, so the name is fitting. Something tested or just a code dump?

Someone releases a prerelease for internal testing? Bam, everyone gets it.
Someone starts abusing the system like SR? Bam, users switch branches without a warning.
Someone doesn't use gh releases, uploading elsewhere? Bam, this prefers live code in whatever state it may be.
Someone forgets or abandons doing releases? Bam, everyone is stuck on old mod.

Looking at the url doesn't tell you anything.

**Comment by ALIENQuake** [comment]
I'm not gonna tell you that those situations might happen because they can. But in the scope of this code/functionality of this microservice which it provide, the luck factor doesn't apply. It will always download "master" or "latest release if it exist". You can achieve exactly the same thing by using two already existing functionality: first, download an latest release and if it fail, use master branch link. But you didn't call those parameters 'luckyrelease' or 'luckymaster', right? So my request was more like and 'alias' to executing two functionality at once.

BTW. Prereleses are included also? I was expecting that they won't. And what's with SR branches?

**Comment by lynxlynxlynx** [comment]
No, those two are deterministic, without unknown fallbacks. It's not that much about code as it is about the user experience, expectations they can have.

prereleases are in by accident, but that's trivial to fix. IR and SR use (pre)releases as two unrelated release channels, breaking the contract.

**Pull request closed without merging**
